directive @cacheControl(maxAge: Int, scope: CacheControlScope) on FIELD_DEFINITION | OBJECT | INTERFACE

enum CacheControlScope {
  PUBLIC
  PRIVATE
}

type Mutation {
  toggleTodo(id: ID!): Todo
  login(name: String!): String
}

type Query {
  todos: [Todo]
}

type Subscription {
  updateTodo: Todo
}

type Todo {
  id: ID
  text: String
  complete: Boolean
  updatedBy: String
}

"""The `Upload` scalar type represents a file upload."""
scalar Upload

